"""Initial migration for beekeeper schema

Revision ID: 2a331f55f3c6
Revises: 
Create Date: 2025-12-04 11:26:02.850724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a331f55f3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='public'
    )
    op.create_index(op.f('ix_public_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False, schema='public')
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_user_id', name='unique_user_provider_account'),
    schema='public'
    )
    op.create_index(op.f('ix_public_social_accounts_id'), 'social_accounts', ['id'], unique=False, schema='public')
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tokens_id'), 'tokens', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tokens_jti'), 'tokens', ['jti'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tokens_token'), 'tokens', ['token'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='public'
    )
    op.create_index(op.f('ix_public_verification_tokens_id'), 'verification_tokens', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_verification_tokens_id'), table_name='verification_tokens', schema='public')
    op.drop_table('verification_tokens', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_tokens_token'), table_name='tokens', schema='public')
    op.drop_index(op.f('ix_public_tokens_jti'), table_name='tokens', schema='public')
    op.drop_index(op.f('ix_public_tokens_id'), table_name='tokens', schema='public')
    op.drop_table('tokens', schema='public')
    op.drop_index(op.f('ix_public_social_accounts_id'), table_name='social_accounts', schema='public')
    op.drop_table('social_accounts', schema='public')
    op.drop_index(op.f('ix_public_password_reset_tokens_id'), table_name='password_reset_tokens', schema='public')
    op.drop_table('password_reset_tokens', schema='public')
    # ### end Alembic commands ###